# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saturn/Salute

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saturn/Salute

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saturn/Salute/CMakeFiles /home/saturn/Salute//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saturn/Salute/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saturn/Salute/CMakeFiles /home/saturn/Salute//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saturn/Salute/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Salute

# Build rule for target.
Salute: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Salute
.PHONY : Salute

# fast build rule for target.
Salute/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/build
.PHONY : Salute/fast

#=============================================================================
# Target rules for targets named CMakeFiles

# Build rule for target.
CMakeFiles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMakeFiles
.PHONY : CMakeFiles

# fast build rule for target.
CMakeFiles/fast:
	$(MAKE) $(MAKESILENT) -f submodules/rapidxml/CMakeFiles/CMakeFiles.dir/build.make submodules/rapidxml/CMakeFiles/CMakeFiles.dir/build
.PHONY : CMakeFiles/fast

#=============================================================================
# Target rules for targets named Framework

# Build rule for target.
Framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Framework
.PHONY : Framework

# fast build rule for target.
Framework/fast:
	$(MAKE) $(MAKESILENT) -f Framework/CMakeFiles/Framework.dir/build.make Framework/CMakeFiles/Framework.dir/build
.PHONY : Framework/fast

src/elements/header.o: src/elements/header.cpp.o
.PHONY : src/elements/header.o

# target to build an object file
src/elements/header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/header.cpp.o
.PHONY : src/elements/header.cpp.o

src/elements/header.i: src/elements/header.cpp.i
.PHONY : src/elements/header.i

# target to preprocess a source file
src/elements/header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/header.cpp.i
.PHONY : src/elements/header.cpp.i

src/elements/header.s: src/elements/header.cpp.s
.PHONY : src/elements/header.s

# target to generate assembly for a file
src/elements/header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/header.cpp.s
.PHONY : src/elements/header.cpp.s

src/elements/input.o: src/elements/input.cpp.o
.PHONY : src/elements/input.o

# target to build an object file
src/elements/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/input.cpp.o
.PHONY : src/elements/input.cpp.o

src/elements/input.i: src/elements/input.cpp.i
.PHONY : src/elements/input.i

# target to preprocess a source file
src/elements/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/input.cpp.i
.PHONY : src/elements/input.cpp.i

src/elements/input.s: src/elements/input.cpp.s
.PHONY : src/elements/input.s

# target to generate assembly for a file
src/elements/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/input.cpp.s
.PHONY : src/elements/input.cpp.s

src/elements/square.o: src/elements/square.cpp.o
.PHONY : src/elements/square.o

# target to build an object file
src/elements/square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/square.cpp.o
.PHONY : src/elements/square.cpp.o

src/elements/square.i: src/elements/square.cpp.i
.PHONY : src/elements/square.i

# target to preprocess a source file
src/elements/square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/square.cpp.i
.PHONY : src/elements/square.cpp.i

src/elements/square.s: src/elements/square.cpp.s
.PHONY : src/elements/square.s

# target to generate assembly for a file
src/elements/square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/square.cpp.s
.PHONY : src/elements/square.cpp.s

src/elements/text.o: src/elements/text.cpp.o
.PHONY : src/elements/text.o

# target to build an object file
src/elements/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/text.cpp.o
.PHONY : src/elements/text.cpp.o

src/elements/text.i: src/elements/text.cpp.i
.PHONY : src/elements/text.i

# target to preprocess a source file
src/elements/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/text.cpp.i
.PHONY : src/elements/text.cpp.i

src/elements/text.s: src/elements/text.cpp.s
.PHONY : src/elements/text.s

# target to generate assembly for a file
src/elements/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/elements/text.cpp.s
.PHONY : src/elements/text.cpp.s

src/layers.o: src/layers.cpp.o
.PHONY : src/layers.o

# target to build an object file
src/layers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/layers.cpp.o
.PHONY : src/layers.cpp.o

src/layers.i: src/layers.cpp.i
.PHONY : src/layers.i

# target to preprocess a source file
src/layers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/layers.cpp.i
.PHONY : src/layers.cpp.i

src/layers.s: src/layers.cpp.s
.PHONY : src/layers.s

# target to generate assembly for a file
src/layers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/layers.cpp.s
.PHONY : src/layers.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/terminal.o: src/terminal.cpp.o
.PHONY : src/terminal.o

# target to build an object file
src/terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/terminal.cpp.o
.PHONY : src/terminal.cpp.o

src/terminal.i: src/terminal.cpp.i
.PHONY : src/terminal.i

# target to preprocess a source file
src/terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/terminal.cpp.i
.PHONY : src/terminal.cpp.i

src/terminal.s: src/terminal.cpp.s
.PHONY : src/terminal.s

# target to generate assembly for a file
src/terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/terminal.cpp.s
.PHONY : src/terminal.cpp.s

src/types/clamp.o: src/types/clamp.cpp.o
.PHONY : src/types/clamp.o

# target to build an object file
src/types/clamp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/types/clamp.cpp.o
.PHONY : src/types/clamp.cpp.o

src/types/clamp.i: src/types/clamp.cpp.i
.PHONY : src/types/clamp.i

# target to preprocess a source file
src/types/clamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/types/clamp.cpp.i
.PHONY : src/types/clamp.cpp.i

src/types/clamp.s: src/types/clamp.cpp.s
.PHONY : src/types/clamp.s

# target to generate assembly for a file
src/types/clamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Salute.dir/build.make CMakeFiles/Salute.dir/src/types/clamp.cpp.s
.PHONY : src/types/clamp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CMakeFiles"
	@echo "... Framework"
	@echo "... Salute"
	@echo "... src/elements/header.o"
	@echo "... src/elements/header.i"
	@echo "... src/elements/header.s"
	@echo "... src/elements/input.o"
	@echo "... src/elements/input.i"
	@echo "... src/elements/input.s"
	@echo "... src/elements/square.o"
	@echo "... src/elements/square.i"
	@echo "... src/elements/square.s"
	@echo "... src/elements/text.o"
	@echo "... src/elements/text.i"
	@echo "... src/elements/text.s"
	@echo "... src/layers.o"
	@echo "... src/layers.i"
	@echo "... src/layers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/terminal.o"
	@echo "... src/terminal.i"
	@echo "... src/terminal.s"
	@echo "... src/types/clamp.o"
	@echo "... src/types/clamp.i"
	@echo "... src/types/clamp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

